name: Build and Push Docker Image

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: admiro
          password: SUZANA100

      - name: Build Docker image
        run: docker build -t admiro/book:latest .

      - name: Log in to PostgreSQL
        run: docker login -u postgres -p 1234qwer.

      - name: Run Docker container with PostgreSQL
        run: |
          docker run -d \
            --name postgres-container \
            -e POSTGRES_DB=book \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=1234qwer. \
            -p 5432:5432 \
            postgres:latest

      - name: Wait for PostgreSQL to start
        run: sleep 15  # Aguarda 15 segundos para o PostgreSQL inicializar completamente

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: admiro/book:latest
